### PR TITLE
Fixes frozen GUI when updating alert tree in non EDT

### LINKED ISSUE #5259: GUI hang (and NPE exceptions) when using Context Alert Filters
**Describe the bug**

ZAP UI & API freezes when running automated active scan. Suspect is `alertFilters` addon based on log.

My command to start ZAP UI:
```
java -XX:MetaspaceSize=128M -XX:MaxMetaspaceSize=256M  \
-jar /home/user1/ZAP_2.7.0/zap.7.0.jar \
-port 8081 \
-dir /home/user1/.ZAP \
-installdir /home/user1/ZAP_2.7.0 \
-config api.disablekey=true \
-config dirs=/var/www/myproject/nodirectaccess/cron/ProcessorServer/zap/scripts \
-config scanner.hostPerScan=2 \
-config scanner.threadPerHost=15 \
-config scanner.delayInMs=0 \
-config scanner.injectable=3 \
-config scanner.enabledRPC=63 \
-config scanner.scanHeadersAllRequests=false
```

First error in the logs (Full error is down below);

```
30264 [ZAP-PassiveScanner] ERROR org.zaproxy.zap.extension.alertFilters.ExtensionAlertFilters  - java.lang.NullPointerException
```

**To Reproduce**
Steps to reproduce the behavior (At least, this is how my automated flow works):
1.  Start ZAP UI (v2.7.0 with the command provided above)
2.  Run `core.deleteAllAlerts()`, `ascan.stopAllScans()` and `ascan.removeAllScans()`,
3.  Enable custom zest scripts,
4.  Run `core.newSession()`,
5.  Import ZAP contex.
6.  Run automated passive and active scans.

**Expected behavior**
ZAP UI doesn't freeze

**Screenshots**

**Software versions**
 - ZAP: 2.7.0
 - Add-on: [id=alertFilters, version=7.0.0]
 - OS: Ubuntu 18.04
 - Java: 
```
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```
 - Browser: -

**Errors from the zap.log file**
https://pastebin.com/iYeMu0ps

Please shout how I can provide more details to reproduce this.

** Additional Info **

My context file - https://pastebin.com/2Dehw9vv
Thread dump output - https://pastebin.com/Wv0um8G8

### PR DESCRIPTION
**Pull request by chozzz**
This fixes #5259 by updating alert tree in a different thread when it's not in EDT
+ with the [feedback here](https://github.com/zaproxy/zaproxy/pull/5268#pullrequestreview-216613205) 

Note: This is the same PR that was previously added in #5268

### CODE REVIEW

File: src/org/zaproxy/zap/extension/alert/ExtensionAlert.java [hunk 1]
```diff
@@ -433,9 +433,28 @@ public void displayAlert(Alert alert) {
     }
 
     public void updateAlertInTree(Alert originalAlert, Alert alert) {
-        if (Constant.isLowMemoryOptionSet()) {
+        if (getView() == null || EventQueue.isDispatchThread()) {
```
Comment (thc202) [inline src/org/zaproxy/zap/extension/alert/ExtensionAlert.java]: Added to wrong if statement?

Comment (chozzz) [reply src/org/zaproxy/zap/extension/alert/ExtensionAlert.java]: Ahh yep - fixing it

File: src/org/zaproxy/zap/extension/alert/ExtensionAlert.java [hunk 2]
```diff
@@ -433,9 +433,28 @@ public void displayAlert(Alert alert) {
     }
 
     public void updateAlertInTree(Alert originalAlert, Alert alert) {
-        if (Constant.isLowMemoryOptionSet()) {
+        if (getView() == null || Constant.isLowMemoryOptionSet()) {
```
Comment (thc202) [inline src/org/zaproxy/zap/extension/alert/ExtensionAlert.java]: I actually meant the view check to be in the following if statement, we do want to update the tree model in the deamon too (just not in the EDT, since it's not needed).

**Comment by thc202** [comment]
Remaining comment addressed.

**Comment by thc202** [comment]
Thanks for the fix!
