### PR TITLE
Restore active scanning everything in scope

### LINKED ISSUE #6102: Error starting Active Scan in "Everything in Scope" mode.
**Describe the bug**
With 3 contexts in scope, starting Active Scan in "Everything in Scope" mode produces an error, and no scanning occurs. The following is written to the log:

425550872 [AWT-EventQueue-0] INFO org.parosproxy.paros.core.scanner.Scanner  - scanner started
425550873 [Thread-3781] ERROR org.parosproxy.paros.core.scanner.Scanner  - An error occurred while active scanning:
java.lang.NullPointerException
	at org.zaproxy.zap.model.StructuralSiteNode.isRoot(StructuralSiteNode.java:77)
	at org.parosproxy.paros.core.scanner.Scanner.scan(Scanner.java:231)
	at org.parosproxy.paros.core.scanner.Scanner.run(Scanner.java:208)
	at java.lang.Thread.run(Thread.java:748)

**To Reproduce**
1. Create 3 Contexts, configure each context to be in scope
2. Open the Active Scan wizard
3. For Staring Point field, click Select button and choose the "Everything in Scope" option
4. Finish the wizard and click the button to start the scan.
5. Error is written to log (see above) and no scanning takes place.

**Expected behavior**
Expect Active Scan to run, scanning all URLs currently in scope

**Screenshots**

**Software versions**
 - ZAP: 2.9.0
 - OS: Linux Mint 19.3
 - Java: openjdk version "1.8.0_252"
 - Browser: n/a

**Errors from the zap.log file**

425550872 [AWT-EventQueue-0] INFO org.parosproxy.paros.core.scanner.Scanner  - scanner started
425550873 [Thread-3781] ERROR org.parosproxy.paros.core.scanner.Scanner  - An error occurred while active scanning:
java.lang.NullPointerException
	at org.zaproxy.zap.model.StructuralSiteNode.isRoot(StructuralSiteNode.java:77)
	at org.parosproxy.paros.core.scanner.Scanner.scan(Scanner.java:231)
	at org.parosproxy.paros.core.scanner.Scanner.run(Scanner.java:208)
	at java.lang.Thread.run(Thread.java:748)

**Additional context**
n/a

**Would you like to help fix this issue?**
Yes.

### PR DESCRIPTION
**Pull request by thc202**
Do not create a `Target` with invalid start node (i.e. null node), just
ignore it (has no special meaning).
Prevent constructing a `StructuralSiteNode` with a null node, to fail
early as possible.

Fix #6102.

### CODE REVIEW

File: zap/src/test/java/org/zaproxy/zap/model/TargetUnitTest.java [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+import static org.hamcrest.Matchers.nullValue;
+
+import org.junit.jupiter.api.Test;
+import org.parosproxy.paros.model.SiteNode;
+
+/** Unit test for {@link Target}. */
+class TargetUnitTest {
+
+    @Test
+    void shouldNotSetNullSiteNodeWhenConstructing() {
```
Comment (kingthorin) [inline zap/src/test/java/org/zaproxy/zap/model/TargetUnitTest.java:33]: These two test methods confuse me. They're named as if null shouldn't be accepted but then assert a null result.

Comment (thc202) [reply zap/src/test/java/org/zaproxy/zap/model/TargetUnitTest.java:33]: That's because they are expected to still be null, before the changes the (wrapped) site node would be added to the list of the start nodes which would make it non-null. The assert for the start node getter is just to exercising it, i.e. still works properly in this specific case.

**Review by kingthorin — APPROVED** [review]

**Review by psiinon — APPROVED** [review]
