### PR TITLE
quick fix for json variant parser

### LINKED ISSUE #3895: JSON Input Vector fails if string has quoted chars
There seems to be a very fundamental issue with the JSON variant parser. The following HTTP post body causes an exception when an active scan is started with the following request (only POST parameter chosen):

	POST http://example.com/ HTTP/1.1
	Connection: keep-alive
	Content-Type: application/json
	Content-Length: 12
	Proxy-Connection: Keep-Alive
	Host: example.com
	
	{"foo":"\""}

ZAP stacktrace when a scanner is run on the request:

	3109792 [ZAP-ActiveScanner-0] WARN org.parosproxy.paros.core.scanner.VariantJSONQuery  - Failed to parse the request body: Object not ended with '}' or ']' at position 11
	java.lang.IllegalArgumentException: Object not ended with '}' or ']' at position 11
		at org.parosproxy.paros.core.scanner.VariantJSONQuery.parseObject(Unknown Source)
		at org.parosproxy.paros.core.scanner.VariantJSONQuery.parseContent(Unknown Source)
		at org.parosproxy.paros.core.scanner.VariantAbstractRPCQuery.setRequestContent(Unknown Source)
		at org.parosproxy.paros.core.scanner.VariantAbstractRPCQuery.setMessage(Unknown Source)
		at org.parosproxy.paros.core.scanner.AbstractAppParamPlugin.scan(Unknown Source)
		at org.parosproxy.paros.core.scanner.AbstractPlugin.run(Unknown Source)
		at java.lang.Thread.run(Thread.java:745)

My versions:

	ZAP 2.6.0
	Active scanner release quality rules version 26
	Java 1.8.0_77

### PR DESCRIPTION
**Pull request by juhakivekas**
Fixes #3895, but not #3322 
Also fixes minor bug that causes the filed name to include the last quotation mark. It's the added `-1` and it came up when writing tests.

### CODE REVIEW

File: test/org/parosproxy/paros/core/scanner/VariantJSONQueryTest.java [hunk 1]
```diff
@@ -0,0 +1,75 @@
+package org.parosproxy.paros.core.scanner;
```
Comment (kingthorin) [inline test/org/parosproxy/paros/core/scanner/VariantJSONQueryTest.java]: Should probably have the standard license header

File: src/org/parosproxy/paros/core/scanner/VariantJSONQuery.java [hunk 2]
```diff
@@ -189,8 +190,11 @@ private void parseValue(String fieldName) {
         // Check if the value is a string        
         if (chr == QUOTATION_MARK) {
             int beginToken = sr.getPosition();
-            while ((chr = sr.read()) != QUOTATION_MARK) {
-                if (chr == -1) {
+            while (true) {
```
Comment (thc202) [inline src/org/parosproxy/paros/core/scanner/VariantJSONQuery.java]: Worth extracting a method and change the read of the property name to also use it (to fixing that one as well).

File: src/org/parosproxy/paros/core/scanner/VariantJSONQuery.java [hunk 3]
```diff
@@ -189,8 +190,11 @@ private void parseValue(String fieldName) {
         // Check if the value is a string        
         if (chr == QUOTATION_MARK) {
             int beginToken = sr.getPosition();
-            while ((chr = sr.read()) != QUOTATION_MARK) {
-                if (chr == -1) {
+            while (true) {
+                chr = sr.read();
+                if (chr == BACKSLASH) { sr.read(); }
```
Comment (thc202) [inline src/org/parosproxy/paros/core/scanner/VariantJSONQuery.java]: The statements should be in a new line (just a matter of consistency with the rest of the code).

File: test/org/parosproxy/paros/core/scanner/VariantJSONQueryTest.java [hunk 4]
```diff
@@ -0,0 +1,75 @@
...
+import java.util.List;
+
+import static org.hamcrest.Matchers.empty;
+import static org.hamcrest.Matchers.is;
+import static org.junit.Assert.assertThat;
+
+/**
+ * Unit test for {@link VariantJSONQuery}.
+ */
+public class VariantJSONQueryTest {
```
Comment (thc202) [inline test/org/parosproxy/paros/core/scanner/VariantJSONQueryTest.java]: It should end with `UnitTest` to be automatically picked by Ant test target.

File: test/org/parosproxy/paros/core/scanner/VariantJSONQueryTest.java [hunk 5]
```diff
@@ -0,0 +1,75 @@
...
+        // Given
+        VariantJSONQuery variantJSONQuery = new VariantJSONQuery();
+        // When
+        List<NameValuePair> parameters = variantJSONQuery.getParamList();
+        // Then
+        assertThat(parameters, is(empty()));
+    }
+
+    @Test
+    public void shouldFindStringValueInContent(){
```
Comment (thc202) [inline test/org/parosproxy/paros/core/scanner/VariantJSONQueryTest.java]: I'd be more explicit and say "Object" (or "JsonObject") instead of "Content" (for when the tests check an array).

File: test/org/parosproxy/paros/core/scanner/VariantJSONQueryTest.java [hunk 6]
```diff
@@ -0,0 +1,75 @@
...
+        assertThat(parameters.get(0).getName(), is("foo"));
+        assertThat(parameters.get(0).getValue(), is("bar\""));
+    }
+
+    private HttpMessage getMessageWithBody(String body){
+        try {
+            return new HttpMessage(
+                    new HttpRequestHeader("POST / HTTP/1.1\nHost: www.example.com\nContent-Type: application/json"),
+                    new HttpRequestBody(body));
+        } catch(HttpMalformedHeaderException e) {
```
Comment (thc202) [inline test/org/parosproxy/paros/core/scanner/VariantJSONQueryTest.java]: It's preferable to re-thrown the exception (or don't catch at all). This might start to fail if the parsing is changed (e.g. be stricter).

File: src/org/parosproxy/paros/core/scanner/VariantJSONQuery.java [hunk 7]
```diff
@@ -294,6 +288,23 @@ private void parseToken(String token) {
         }
     }
 
+    private void readEscapedString(){
+        int chr;
+        while (true) {
+            chr = sr.read();
+            if (chr == BACKSLASH) {
+                sr.read();
+                continue;
```
Comment (thc202) [inline src/org/parosproxy/paros/core/scanner/VariantJSONQuery.java]: This statement could be removed (does not add much, it already goes to next cycle).

**Comment by thc202** [comment]
Thank you!

**Comment by kingthorin** [comment]
Thanks @juhakivekas
