### PR TITLE
Handle out of disk space errors better

### LINKED ISSUE #2382: IOException - data file enlarge failed
From https://github.com/zaproxy/zaproxy/issues/2127#issuecomment-164426383, the database "silently" fails (it just logs with warn level) when there's no disk space to increase the data file. At the very least, the user should be informed about that.

See also https://github.com/zaproxy/zaproxy/issues/2127#issuecomment-192188629, for more information.

### LINKED ISSUE #8327: ZAP scanning process become frosen on few days when autoscanning specific site
### Describe the bug

ZAP scanning progress become frosen on few days when autoscanning specific site vps.ua

### Steps to reproduce the behavior

Run ZAP and start autoscan vps.ua URL
Wait few days and observe that scanning progress become frosen on 18%
Click Stop button and observe that Attack button remains disabled, see java trace attached 
[ZAP-gui-hang-during-stop-scan.txt](https://github.com/zaproxy/zaproxy/files/14173638/ZAP-gui-hang-during-stop-scan.txt)

### Expected behavior

scanning progress should not be frosen

### Software versions

ZAP Version: 2.14.0

Installed Add-ons: [[id=alertFilters, version=19.0.0],
[id=ascanrules, version=59.0.0], [id=ascanrulesBeta,
version=48.0.0], [id=authhelper, version=0.10.0],
[id=automation, version=0.35.0], [id=bruteforce,
version=15.0.0], [id=callhome, version=0.10.0],
[id=commonlib, version=1.22.0], [id=coreLang,
version=15.0.0], [id=custompayloads, version=0.13.0],
[id=database, version=0.3.0], [id=diff, version=14.0.0],
[id=directorylistv1, version=7.0.0], [id=directorylistv2_3,
version=4.0.0], [id=directorylistv2_3_lc, version=4.0.0],
[id=domxss, version=18.0.0], [id=encoder, version=1.4.0],
[id=exim, version=0.8.0], [id=formhandler, version=6.5.0],
[id=fuzz, version=13.12.0], [id=fuzzdboffensive,
version=5.0.0], [id=gettingStarted, version=16.0.0],
[id=graaljs, version=0.5.0], [id=graphql, version=0.22.0],
[id=help, version=17.0.0], [id=hud, version=0.18.0],
[id=invoke, version=14.0.0], [id=network, version=0.12.0],
[id=oast, version=0.17.0], [id=onlineMenu, version=12.0.0],
[id=openapi, version=39.0.0], [id=portscan, version=10.0.0],
[id=postman, version=0.2.0], [id=pscanrules,
version=55.0.0], [id=pscanrulesBeta, version=36.0.0],
[id=quickstart, version=43.0.0], [id=replacer,
version=16.0.0], [id=reports, version=0.28.0],
[id=requester, version=7.4.0], [id=retest, version=0.8.0],
[id=retire, version=0.30.0], [id=reveal, version=7.0.0],
[id=scripts, version=44.0.0], [id=selenium,
version=15.15.0], [id=soap, version=21.0.0], [id=spider,
version=0.7.0], [id=spiderAjax, version=23.18.0],
[id=sqliplugin, version=15.0.0], [id=svndigger,
version=4.0.0], [id=tips, version=12.0.0], [id=tokengen,
version=15.0.0], [id=wappalyzer, version=21.29.0],
[id=webdriverwindows, version=70.0.0], [id=websocket,
version=30.0.0], [id=zest, version=42.0.0]]

Operating System: Windows 10
Architecture: amd64
Java Version: Eclipse Adoptium 21.0.1
System's Locale: uk_UA
Display Locale: en_GB
Format Locale: uk_UA
Default Charset: UTF-8
ZAP Home Directory: C:\Users\Admin\ZAP\
ZAP Installation Directory: C:\Program Files\ZAP\Zed Attack Proxy\.\
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)

### Screenshots

_No response_

### Errors from the zap.log file

[zaplogs.zip](https://github.com/zaproxy/zaproxy/files/14173657/zaplogs.zip)

### Additional context

_No response_

### Would you like to help fix this issue?

- [ ] Yes

### PR DESCRIPTION
**Pull request by psiinon**
Fixes #2382
Fixes #8327

### CODE REVIEW

**Comment by psiinon** [comment]
Logo
**Checkmarx One – Scan Summary & Details** – [9ef40d2d\-7861\-4178\-9667\-c4a1c75380f8](https://eu.ast.checkmarx.net/projects/641c4d0f-0dae-4786-973b-ead9338157fd/scans?id=9ef40d2d-7861-4178-9667-c4a1c75380f8&branch=psiinon%2Fdisk-space)
### Great job\! No new security vulnerabilities introduced in this pull request


---
Use @Checkmarx to reach out to us for assistance.

Just send a PR comment with `@Checkmarx` followed by a natural language request.

**Examples:** `@Checkmarx how are you able to help me?` `@Checkmarx rescan this PR`

**Comment by thc202** [comment]
Thank you!

File: zap/src/main/java/org/zaproxy/zap/utils/ErrorUtils.java [hunk 1]
```diff
@@ -0,0 +1,135 @@
...
+                if (dbFull) {
+                    errorMsg = Constant.messages.getString("db.space.full");
+                    Stats.incCounter("stats.error.database.full");
+                } else {
+                    errorMsg = Constant.messages.getString("disk.space.full");
+                    Stats.incCounter("stats.error.diskspace.full");
+                }
+
+                LOGGER.error(errorMsg);
+                // Just in case theres not enough space to write the the log
```
Comment (kingthorin) [inline zap/src/main/java/org/zaproxy/zap/utils/ErrorUtils.java]: the the ➡️ to the

Comment (psiinon) [reply zap/src/main/java/org/zaproxy/zap/utils/ErrorUtils.java]: Fixed

**Comment by psiinon** [comment]
Changed to draft - doesnt stop ZAP in daemon mode..

**Comment by psiinon** [comment]
Updated to force exit if no GUI.
