### PR TITLE
Don't use msg from auth script if URI is missing

### LINKED ISSUE #5491: Auth request without request-target from auth script causes exceptions
**Describe the bug**
**Receive NullPointerException while spider with user authentication and HTTPSender enabled **
**To Reproduce**
1. Add Authorization script (https://gist.github.com/aynacisevda/ab3c15304b861297d9dcd1891d2df4fb) and HTTP Sender (https://gist.github.com/aynacisevda/f3053b8ca1ae42e88990d60909a92e28) script
2. Start spider by right click on context
3. Go to spider tab
java.lang.NullPointerException: null

Stack Trace:
java.lang.NullPointerException
	at org.zaproxy.zap.model.SessionStructure.getHostName(SessionStructure.java:384)
	at org.zaproxy.zap.model.SessionStructure.getHostName(SessionStructure.java:378)
	at org.zaproxy.zap.authentication.AuthenticationMethod.isAuthenticated(AuthenticationMethod.java:225)
	at org.zaproxy.zap.authentication.ScriptBasedAuthenticationMethodType$ScriptBasedAuthenticationMethod.authenticate(ScriptBasedAuthenticationMethodType.java:300)
	at org.zaproxy.zap.users.User.authenticate(User.java:265)
	at org.zaproxy.zap.users.User.processMessageToMatchUser(User.java:175)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:578)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:553)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:458)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:428)
	at org.zaproxy.zap.spider.SpiderTask.fetchResource(SpiderTask.java:445)
	at org.zaproxy.zap.spider.SpiderTask.runImpl(SpiderTask.java:218)
	at org.zaproxy.zap.spider.SpiderTask.run(SpiderTask.java:190)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Screenshot:
image

**Software versions**
 - ZAP: 2.8.0
 - OS: Windows 10
 - Java: 1.8.0_192

### PR DESCRIPTION
**Pull request by thc202**
Change `ScriptBasedAuthenticationMethod` to not use the authentication
message if the request does not have the URI (which is required to
process the authentication), also, handle it as a script error.
Add helper method to `ExtensionScript` to handle script errors.

Fix #5491 - Auth request without request-target from auth script causes
exceptions

### CODE REVIEW

File: zap/src/main/java/org/zaproxy/zap/extension/script/ExtensionScript.java [hunk 1]
```diff
@@ -1551,6 +1552,29 @@ private void handleScriptException(ScriptWrapper script, Writer writer, Exceptio
         this.setEnabled(script, false);
     }
 
+    /**
+     * Handles errors caused by scripts.
+     *
+     * <p>The given {@code error} will be written to the writer(s) associated with the given
+     * {@code script}, moreover it will be disabled and flagged that has an error.
```
Comment (kingthorin) [inline zap/src/main/java/org/zaproxy/zap/extension/script/ExtensionScript.java]: `moreover the script will be disabled...`?

Comment (thc202) [reply zap/src/main/java/org/zaproxy/zap/extension/script/ExtensionScript.java]: Tweaked here and in the other method.
