### PR TITLE
Do not disable break buttons if msgs still caught

### LINKED ISSUE #4623: Message caught in Break tab but break buttons remain disabled
Steps to reproduce the issue:
1. Run ZAP with WebSockets add-on;
2. Enable Options > WebSockets > Break on enabled 'all request/response break buttons';
3. Establish a WebSocket connection, e.g. `http://www.websocket.org/echo.html`
4. Start breaking on all requests and responses;
5. Send two WebSocket messages from the client (that end up being echoed by the server);
6. Start stepping (slowly to give time to the server to send the echoes);
7. Note that in the end an echoed message is shown in the Break tab, but the break buttons are disabled, preventing the message from being dispatched or dropped.

Remarks:
 - While the issue is reproducible with WebSocket messages the cause is in a core class, `BreakpointMessageHandler2` (more precisely, around the `synchronized` blocks).
 - It's possible to interact with the caught message using break API.

Thread dump showing the relevant threads blocked:
```
"ZAP-ProxyThread-164" - Thread t@594
   java.lang.Thread.State: BLOCKED
	at org.zaproxy.zap.extension.brk.BreakpointMessageHandler2.handleMessageReceivedFromServer(BreakpointMessageHandler2.java:103)
	- waiting to lock <475c7579> (a java.lang.Object) owned by "ZAP-WS-Listener (remote) 'localhost:3000 (#3)'" t@231
	at org.zaproxy.zap.extension.brk.ExtensionBreak.messageReceivedFromServer(ExtensionBreak.java:600)
	at org.zaproxy.zap.extension.brk.impl.http.ProxyListenerBreak.onHttpResponseReceive(ProxyListenerBreak.java:86)
	at org.parosproxy.paros.core.proxy.ProxyThread.notifyListenerResponseReceive(ProxyThread.java:701)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:522)
	- locked <74073673> (a java.lang.Object)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:318)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- None

"ZAP-WS-Listener (remote) 'localhost:3000 (#3)'" - Thread t@231
   java.lang.Thread.State: TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at org.zaproxy.zap.extension.brk.BreakpointMessageHandler2.waitUntilContinue(BreakpointMessageHandler2.java:124)
	at org.zaproxy.zap.extension.brk.BreakpointMessageHandler2.handleMessageReceivedFromServer(BreakpointMessageHandler2.java:106)
	- locked <475c7579> (a java.lang.Object)
	at org.zaproxy.zap.extension.websocket.brk.WebSocketProxyListenerBreak.onMessageFrame(WebSocketProxyListenerBreak.java:105)
	at org.zaproxy.zap.extension.websocket.WebSocketProxy.notifyMessageObservers(WebSocketProxy.java:685)
	at org.zaproxy.zap.extension.websocket.WebSocketProxy.processRead(WebSocketProxy.java:578)
	at org.zaproxy.zap.extension.websocket.WebSocketListener.run(WebSocketListener.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- locked <55025bf6> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"ZAP-WS-Listener (remote) 'localhost:3000 (#4)'" - Thread t@329
   java.lang.Thread.State: BLOCKED
	at org.zaproxy.zap.extension.brk.BreakpointMessageHandler2.handleMessageReceivedFromServer(BreakpointMessageHandler2.java:103)
	- waiting to lock <475c7579> (a java.lang.Object) owned by "ZAP-WS-Listener (remote) 'localhost:3000 (#3)'" t@231
	at org.zaproxy.zap.extension.websocket.brk.WebSocketProxyListenerBreak.onMessageFrame(WebSocketProxyListenerBreak.java:105)
	at org.zaproxy.zap.extension.websocket.WebSocketProxy.notifyMessageObservers(WebSocketProxy.java:685)
	at org.zaproxy.zap.extension.websocket.WebSocketProxy.processRead(WebSocketProxy.java:578)
	at org.zaproxy.zap.extension.websocket.WebSocketListener.run(WebSocketListener.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- locked <731c0155> (a java.util.concurrent.ThreadPoolExecutor$Worker)
```

ZAP
Version 2.7.0 (and older).

### PR DESCRIPTION
**Pull request by thc202**
Change BreakPanelToolbarFactory to keep track of how many messages are
currently caught to just disable the buttons when none is left. Now the
buttons are no longer disabled after stepping/dropping only when
continuing (which forwards everything) or no messages left.
Remove the boolean parameter from setStep/setDrop and rename to step and
drop, respectively, the parameter is no longer needed the break buttons
are no longer affected (and the parameter was always the same, true).
Update BreakPanel to reflect the changes in the step/drop methods.

Fix #4623 - Message caught in Break tab but break buttons remain
disabled

### CODE REVIEW

File: src/org/zaproxy/zap/extension/brk/BreakPanelToolbarFactory.java [hunk 1]
```diff
@@ -70,6 +70,21 @@
 	private BreakpointsParam breakpointsParams;
 	private int mode = 0;
 
+	/**
+	 * A counter to keep track of how many messages are currently caught, to disable the break buttons when no message is left.
+	 * <p>
+	 * The counter is increased when a {@link #breakpointHit() breakpoint is hit} and decreased when a message is no longer
+	 * {@link #isHoldMessage() being hold}.
```
Comment (kingthorin) [inline src/org/zaproxy/zap/extension/brk/BreakPanelToolbarFactory.java]: It's really minor but this should be "held"

**Comment by thc202** [comment]
Corrected, thank you.
