### PR TITLE
Use TreeCellRenderers to prevent HTML injection issues

### LINKED ISSUE #3224: HTML injection in "Alert" tab
Reported via bugcrowd, but being copied here as its a self XSS and therefore not really a security issue.

>     To reproduce please create new alert or edit existed. In first field please type this:
>     <h1>HTML injection</h1><br>
>     Look at Alert_xss.png
>     Than click ok and you will see our HTML injection in Alert tab (Look at Alert_xss1.png)
>     Note, that this vulnerability potentialy could be used to steal another issues from "Alert" tab.
> 
>     I could not exploit it now remoutly - when ZAP scans my site (only manual injection). But i think it could be more exploitable with some Add-ons.

### PR DESCRIPTION
**Pull request by psiinon**
Fixes #3224

### CODE REVIEW

File: src/org/zaproxy/zap/view/SiteMapTreeCellRenderer.java [hunk 1]
```diff
@@ -71,23 +77,25 @@ public Component getTreeCellRendererComponent(JTree tree, Object value,
...
-	            setPreferredSize(null);	// clears the prefered size, making the node visible
-	            super.getTreeCellRendererComponent(tree, value, sel, expanded, leaf, row, hasFocus);
-	        }
+			if( node.isFiltered()) {
+				// Hide the node
+				setPreferredSize( new Dimension(0, 0) );
+			} else {
+				setPreferredSize(null);	// clears the prefered size, making the node visible
+				super.getTreeCellRendererComponent(tree, value, sel, expanded, leaf, row, hasFocus);
+			}
```
Comment (kingthorin) [inline src/org/zaproxy/zap/view/SiteMapTreeCellRenderer.java]: Are these white space changes necessary?

File: src/org/zaproxy/zap/view/SiteMapTreeCellRenderer.java [hunk 2]
```diff
@@ -121,17 +129,54 @@ public Component getTreeCellRendererComponent(JTree tree, Object value,
 					// Add lock icon to site nodes with https
 					icon.add(LOCK_OVERLAY_ICON);
 				}
-				setIcon(DisplayUtils.getScaledIcon(icon));
+				
+				//setIcon(DisplayUtils.getScaledIcon(icon));
```
Comment (kingthorin) [inline src/org/zaproxy/zap/view/SiteMapTreeCellRenderer.java]: This comment could be removed?

File: src/org/zaproxy/zap/view/SiteMapTreeCellRenderer.java (hunk 1 above)
Comment (kingthorin) [inline src/org/zaproxy/zap/view/SiteMapTreeCellRenderer.java]: Are these white space changes necessary?

File: src/org/parosproxy/paros/core/scanner/Alert.java [hunk 3]
```diff
@@ -688,6 +692,31 @@ public int getRisk() {
...
     
+    /**
+     * Gets the correctly scaled icon for this alert.
+     * @return the correctly scaled icon for this alert
+     * @since TODO add version
+     */
+    public ImageIcon getIcon() {
+        if (confidence == Alert.CONFIDENCE_FALSE_POSITIVE) {
+            // Special case - theres no risk - use the green flag
+            return DisplayUtils.getScaledIcon(new ImageIcon(Constant.OK_FLAG_IMAGE_URL));
```
Comment (thc202) [inline src/org/parosproxy/paros/core/scanner/Alert.java]: It could use the same method as the other statements.

File: src/org/zaproxy/zap/view/SiteMapTreeCellRenderer.java [hunk 4]
```diff
@@ -58,9 +62,11 @@
 	private static Logger log = Logger.getLogger(SiteMapPanel.class);
 
 	private List<SiteMapListener> listeners;
+	private JPanel component; 
 
 	public SiteMapTreeCellRenderer(List<SiteMapListener> listeners) {
 		this.listeners = listeners;
+		this.component = new JPanel();
```
Comment (thc202) [inline src/org/zaproxy/zap/view/SiteMapTreeCellRenderer.java]: There's an extra spacing between the nodes, that might needs some tweaks (to look as before).

File: src/org/zaproxy/zap/view/SiteMapTreeCellRenderer.java [hunk 5]
```diff
@@ -71,23 +77,25 @@ public Component getTreeCellRendererComponent(JTree tree, Object value,
 			boolean sel, boolean expanded, boolean leaf, int row,
 			boolean hasFocus) {
 
+		component = new JPanel();
```
Comment (thc202) [inline src/org/zaproxy/zap/view/SiteMapTreeCellRenderer.java]: It could call `component.removeAll()` instead.

File: src/org/zaproxy/zap/view/SiteMapTreeCellRenderer.java [hunk 6]
```diff
@@ -71,23 +77,25 @@ public Component getTreeCellRendererComponent(JTree tree, Object value,
...
+		component.setOpaque(false);
```
Comment (thc202) [inline src/org/zaproxy/zap/view/SiteMapTreeCellRenderer.java]: This can be called once (in the constructor).

File: src/org/zaproxy/zap/view/SiteMapTreeCellRenderer.java [hunk 7]
```diff
@@ -71,23 +77,25 @@ public Component getTreeCellRendererComponent(JTree tree, Object value,
...
+				setPreferredSize( new Dimension(0, 0) );
+			} else {
+				setPreferredSize(null);	// clears the prefered size, making the node visible
+				super.getTreeCellRendererComponent(tree, value, sel, expanded, leaf, row, hasFocus);
+			}
 
 			// folder / file icons with scope 'target' if relevant
 			if (node.isRoot()) {
-				setIcon(DisplayUtils.getScaledIcon(ROOT_ICON));	// 'World' icon
+				component.add(new JLabel(DisplayUtils.getScaledIcon(DisplayUtils.getScaledIcon(ROOT_ICON)))); // 'World' icon
```
Comment (thc202) [inline src/org/zaproxy/zap/view/SiteMapTreeCellRenderer.java]: Could call warp here too?

**Comment by psiinon** [comment]
Hopefully addressed all of the comments. The Sites tree spacing isnt exactly the same as before (its actually slightly closer together) but I think it looks ok - wdyt?

**Comment by thc202** [comment]
Sites tree spacing looks good to me.
