### PR TITLE
Spider: Import tags, csp and msapplication-config attributes of meta, strings in html

### LINKED ISSUE #7209: Crawl Maze: Fix any 5 missing URLs
Fix any 5 of the failing results on https://www.zaproxy.org/docs/scans/crawlmaze/

It is important to note that the priority here is to improve the ZAP scan results against real work apps so any improvements should be generic rather than tailored for Crawl Maze.

As always all PRs should include full unit tests.

Comment on this issue with the URLs you would like to be assigned - they must not already be assigned on https://github.com/zaproxy/zaproxy/issues/7152

### PR DESCRIPTION
**Pull request by karthikuj**
This PR fixes the following false negatives of the crawlmaze tests:

```
/test/html/head/import/implementation.found
/test/html/head/meta/content-csp.found
/test/html/head/meta/content-pinned-websites.found
/test/html/misc/string/url-string.found
/test/html/misc/string/string-known-extension.pdf
```

Fixes #7209

### CODE REVIEW

File: zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java [hunk 1]
```diff
@@ -41,13 +44,21 @@ public class SpiderHtmlParser extends SpiderParser {
...
+                    "(?:url\\s*=|report-uri)\\s*[\"']?([^;'\"]+)", Pattern.CASE_INSENSITIVE);
 
     private static final Pattern PLAIN_COMMENTS_URL_PATTERN =
             Pattern.compile(
-                    "(?:http(?:s?):)?//[^\\x00-\\x1f\"'\\s<>#()\\[\\]{}]+",
+                    "(?:http(?:s?):)?/?/[^\\x00-\\x1f\"'\\s<>#()\\[\\]{}]+",
                     Pattern.CASE_INSENSITIVE);
 
+    /** The Constant log. */
+    private static final Logger log = LogManager.getLogger(SpiderHtmlParser.class);
```
Comment (thc202) [inline zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java:56]: Should be removed.

File: zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java [hunk 2]
```diff
@@ -41,13 +44,21 @@ public class SpiderHtmlParser extends SpiderParser {
...
+
+    /** Element not in jericho html parser */
```
Comment (thc202) [inline zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java:58]: Not really needed.

File: zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java [hunk 3]
```diff
@@ -41,13 +44,21 @@ public class SpiderHtmlParser extends SpiderParser {
...
+    private static final String IMPORT_TAG = "IMPORT";
+
+    private static Boolean isBaseTagSet = false;
```
Comment (thc202) [inline zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java:61]: `private boolean baseTagSet;`

File: zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java [hunk 4]
```diff
@@ -41,13 +44,21 @@ public class SpiderHtmlParser extends SpiderParser {
...
     /** The Constant URL_PATTERN defining the pattern for a meta url. */
     static final Pattern URL_PATTERN =
-            Pattern.compile("url\\s*=\\s*[\"']?([^;'\"]+)", Pattern.CASE_INSENSITIVE);
+            Pattern.compile(
+                    "(?:url\\s*=|report-uri)\\s*[\"']?([^;'\"]+)", Pattern.CASE_INSENSITIVE);
 
     private static final Pattern PLAIN_COMMENTS_URL_PATTERN =
             Pattern.compile(
-                    "(?:http(?:s?):)?//[^\\x00-\\x1f\"'\\s<>#()\\[\\]{}]+",
+                    "(?:http(?:s?):)?/?/[^\\x00-\\x1f\"'\\s<>#()\\[\\]{}]+",
```
Comment (thc202) [inline zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java:52]: I don't think we should include everything that has a slash. This also matches invalid URLs e.g. `http:/example.com/`.

File: zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java (hunk 1 above)
Comment (karthikuj) [reply zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java]: Yes, I forgot to remove it, added for debugging purposes. Now removed :)

File: zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java (hunk 2 above)
Comment (karthikuj) [reply zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java:56]: Removed :)

File: zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java (hunk 3 above)
Comment (karthikuj) [reply zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java]: Done :)

File: zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java (hunk 4 above)
Comment (karthikuj) [reply zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java]: Updated the regex and now it should ideally match all cases. Please check :)

File: zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java (hunk 2 above)
Comment (thc202) [reply zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java:56]: Still present.

Comment (karthikuj) [reply zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java]: This time, removed for sure.

File: zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java (hunk 3 above)
Comment (karthikuj) [reply zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java]: Changed

File: zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java [hunk 5]
```diff
@@ -217,25 +224,78 @@ private boolean parseSource(HttpMessage message, Source source, int depth, Strin
...
+                        HTMLElementName.P,
+                        HTMLElementName.TITLE,
+                        HTMLElementName.H1,
+                        HTMLElementName.H2,
+                        HTMLElementName.H3,
+                        HTMLElementName.H4,
+                        HTMLElementName.H5,
+                        HTMLElementName.H6,
+                        HTMLElementName.LI,
+                        HTMLElementName.BLOCKQUOTE);
```
Comment (thc202) [inline zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java:246]: Should be extracted a constant, although I'm not quite sure about the choices. Are they based on real examples?

File: zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java [hunk 6]
```diff
@@ -217,25 +224,78 @@ private boolean parseSource(HttpMessage message, Source source, int depth, Strin
...
+
+        for (String tag : elementsWithText) {
+            elements = source.getAllElements(tag);
+            for (Element el : elements) {
+                Source s = new Source(el.getContent());
+                if (!parseSource(message, s, depth, baseURL)) {
```
Comment (thc202) [inline zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java:252]: Why?

File: zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java [hunk 7]
```diff
@@ -217,25 +224,78 @@ private boolean parseSource(HttpMessage message, Source source, int depth, Strin
...
+                    Matcher matcher = PLAIN_COMMENTS_URL_PATTERN.matcher(s.toString());
+                    while (matcher.find()) {
+                        String foundMatch = matcher.group().trim();
+                        if (baseTagSet) {
+                            if (!baseURL.endsWith("/")) {
+                                baseURL += "/";
```
Comment (thc202) [inline zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java:258]: Do not change the `baseURL` use other local variable instead, this can also be done just once before the loop.

File: zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java [hunk 8]
```diff
@@ -217,25 +224,78 @@ private boolean parseSource(HttpMessage message, Source source, int depth, Strin
...
+                            }
+                            if (('/' == foundMatch.charAt(0)) && (0 != foundMatch.indexOf("//"))) {
```
Comment (thc202) [inline zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java:260]:
```suggestion
                            if (foundMatch.charAt(0) == '/' && foundMatch.indexOf("//") != 0) {
```

File: zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java [hunk 9]
```diff
@@ -217,25 +224,78 @@ private boolean parseSource(HttpMessage message, Source source, int depth, Strin
...
                     Matcher matcher = URL_PATTERN.matcher(content);
                     if (matcher.find()) {
                         String url = matcher.group(1);
                         processURL(message, depth, url, baseURL);
                         resourcesfound = true;
                     }
                 }
+            } else if (name != null && content != null) {
+                if (name.equalsIgnoreCase("msapplication-config")
+                        && !content.equalsIgnoreCase("none")) {
```
Comment (thc202) [inline zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java:295]: Merge the ifs, the name null check can be dropped if used the literal in the left hand side.

File: zap/src/test/resources/org/zaproxy/zap/spider/parser/html/MetaElementsSpiderHtmlParser.html [hunk 10]
```diff
@@ -19,6 +19,18 @@
...
+<meta http-equiv="Content-Security-Policy" content="script-src 'self'; report-uri //meta.example.com:4444/meta/base/csp/scheme">
+<meta http-equiv="Content-Security-Policy" content="script-src 'self'; report-uri https://meta.example.com/meta/csp">
+<meta http-equiv="Content-Security-Policy" content="script-src 'self'; report-uri meta/csp/refresh/relative">
+<meta http-equiv="Content-Security-Policy" content="script-src 'self'; report-uri ftp://meta.example.com/meta/csp/">
+
+<meta name="msapplication-config" content="/meta/msapplication">
+<meta name="msapplication-config" content="//meta.example.com:1337/meta/msapplication">
+<meta name="msapplication-config" content="https://meta.example.com/meta/msapplication">
+<meta name="msapplication-config" content="meta/msapplication/refresh/relative">
+<meta name="msapplication-config" content="ftp://meta.example.com/meta/msapplication/refresh">
```
Comment (thc202) [inline zap/src/test/resources/org/zaproxy/zap/spider/parser/html/MetaElementsSpiderHtmlParser.html:32]: Missing the following cases:
 - Name empty.
 - Other name than `msapplication-config`.
 - Name `msapplication-config` and content `none` and empty.

File: zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java (hunk 4 above)
Comment (thc202) [reply zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java]: Introduce a new regex just for inline content, this is now matching `/a` in plain comments which didn't before.

**Comment by thc202** [comment]
The help should be updated with the new elements/attributes covered by this pull request (should be done in the `zap-extensions` repo).

**Comment by thc202** [comment]
It has conflicts now.

**Comment by psiinon** [comment]
@karthikuj ping :)

**Comment by karthikuj** [comment]
Hello Devs, I'm currently traveling, I will start working on this from the next week, sorry for any inconveniences this may cause.

**Comment by thc202** [comment]
No inconveniences, just checking. Thank you.

**Comment by karthikuj** [comment]
> The latest changes don’t compile and some of the earlier comments/fixes seem to be missing.

Yes, I am aware, pushed by mistake

**Comment by kingthorin** [comment]
Okay no problem. Hang in there, I’m sure you’ve got this 👍

File: zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java (hunk 4 above)
Comment (karthikuj) [reply zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java]: Done

File: zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java (hunk 5 above)
Comment (karthikuj) [reply zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java]: Made it a constant. Some of them are based on real examples, like <p>, <title> and <li>. But the heading tags and blockquote ones are peculiar in my opinion too. Shall I remove them?

File: zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java (hunk 6 above)
Comment (karthikuj) [reply zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java]: Changed this.

File: zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java (hunk 7 above)
Comment (karthikuj) [reply zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java]: Done.

File: zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java (hunk 8 above)
Comment (karthikuj) [reply zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java]: Done.

File: zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java (hunk 9 above)
Comment (karthikuj) [reply zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java]: Done.

File: zap/src/test/resources/org/zaproxy/zap/spider/parser/html/MetaElementsSpiderHtmlParser.html (hunk 10 above)
Comment (karthikuj) [reply zap/src/test/resources/org/zaproxy/zap/spider/parser/html/MetaElementsSpiderHtmlParser.html:32]: Added

**Comment by thc202** [comment]
There are tests failing in Java 8 and 11 (might be because of the empty string check being done with `==` instead of `equals`?).

Will check the latest changes later.

File: zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java (hunk 2 above)
Comment (kingthorin) [reply zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java:87]: Still

File: zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java (hunk 1 above)
Comment (kingthorin) [reply zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java:85]: Still present

File: zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java (hunk 2 above)
Comment (karthikuj) [reply zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java:82]: Added it back last time for debugging, removed it again.

File: zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java (hunk 1 above)
Comment (karthikuj) [reply zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java]: Added it back last time for debugging, removed it again.

File: zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java (hunk 2 above)
Comment (kingthorin) [reply zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java]: This one is about the comment not the logger

Comment (karthikuj) [reply zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java]: Yes, and it has now been removed :)

File: zap/src/test/resources/org/zaproxy/zap/spider/parser/html/MetaElementsSpiderHtmlParser.html (hunk 10 above)
Comment (thc202) [reply zap/src/test/resources/org/zaproxy/zap/spider/parser/html/MetaElementsSpiderHtmlParser.html:32]: The case with content as `none` was not added.

File: zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java (hunk 5 above)
Comment (thc202) [reply zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java]: Can be kept as is, we'll see how it goes.

File: zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java (hunk 8 above)
Comment (thc202) [reply zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java]: There are still some redundant parentheses.

File: zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java [hunk 11]
```diff
@@ -270,25 +295,64 @@ private boolean parseSource(HttpMessage message, Source source, int depth, Strin
...
+                    processAttributeElement(message, depth, baseURL, el, "implementation");
+        }
+
+        // Process content of container tags which hold text
+        String baseUrlForText = baseURL;
+        for (String tag : elementsWithText) {
+            elements = source.getAllElements(tag);
+            for (Element el : elements) {
+                Source s = new Source(el.getContent());
+                Matcher matcher = INLINE_CONTENT_URL_PATTERN.matcher(s.toString());
```
Comment (thc202) [inline zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java:311]: Should just do `el.getContent().toString()`

Comment (kingthorin) [reply zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java]: In the matcher, no need to intermediate my store in s

File: zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java (hunk 8 above)
Comment (karthikuj) [reply zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java]: Removed.

File: zap/src/test/resources/org/zaproxy/zap/spider/parser/html/MetaElementsSpiderHtmlParser.html (hunk 10 above)
Comment (karthikuj) [reply zap/src/test/resources/org/zaproxy/zap/spider/parser/html/MetaElementsSpiderHtmlParser.html:32]: Added it to the `<!-- Ignored: -->` section.

File: zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java (hunk 11 above)
Comment (karthikuj) [reply zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java]: Changed.

Comment (kingthorin) [reply zap/src/main/java/org/zaproxy/zap/spider/parser/SpiderHtmlParser.java]: 👍

**Comment by thc202** [comment]
Could you fix up the commits?

**Comment by karthikuj** [comment]
> Could you fix up the commits?

Can you please explain this? How do I do this?

Thank you.

**Comment by thc202** [comment]
Execute the following:
```sh
git fetch upstream && git merge --no-edit upstream/main && git reset --soft upstream/main && git commit -C dc31711
```
Review all good and force push.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Review by psiinon — APPROVED** [review]

**Comment by psiinon** [comment]
Thanks you @karthikuj  - we've just rerun the Crawl Maze tests and can confirm that ZAP finds these new URLs.
The results on the website should be updated very soon.
I dont think you are on the [ZAP credits](https://www.zaproxy.org/docs/desktop/credits/) yet are you?
If not then can you let us know the name you'd like us to use there, and optionally a link (eg to twitter, linkedin or whatever) and the company you work for (if relevant).
Many thanks!

**Comment by psiinon** [comment]
Like this? https://github.com/zaproxy/zap-core-help/pull/455/files 😄 
Do you have a twitter account?
I was going to tweet about the score improvement - if not shall I use your website link?

**Comment by karthikuj** [comment]
Yes awesome.
I do have a twitter handle - https://twitter.com/5up3r541y4n :smile:

**Comment by psiinon** [comment]
https://twitter.com/zaproxy/status/1557384490347073537 😁

**Comment by psiinon** [comment]
@karthikuj dont forget to claim the bounty!

**Comment by karthikuj** [comment]
Wow, thank you so much guys, I'm honored :smile: :grin: 
And yes, will claim the bounty!!
