### PR TITLE
Use alert refs in HTTP Response Code Errors script

### LINKED ISSUE #9273: Add refs for Alert on HTTP Response Code Errors script rule
The "Alert on HTTP Response Code Errors" script scan rule raises different alerts with exactly the same alert reference.
It should be changed to use unique references.
Note that this rule is defined in 2 places:
* https://github.com/zaproxy/community-scripts/blob/main/httpsender/Alert%20on%20HTTP%20Response%20Code%20Errors.js
* https://github.com/zaproxy/zaproxy/blob/main/docker/scripts/scripts/httpsender/Alert_on_HTTP_Response_Code_Errors.js

It is worth noting that this alert (and Alert_on_Unexpected_Content_Types.js) are not shown on https://www.zaproxy.org/docs/alerts/

Ideally they should generate examples which can be detected automatically, or failing that we could just manually create the relevant pages?

### PR DESCRIPTION
**Pull request by ridhimamathur**
Fixes #9273

The "Alert on HTTP Response Code Errors" script raised alerts with identical references.

This change adds a reference based on the HTTP response code so each alert has a unique reference.

### CODE REVIEW

**Comment by psiinon** [comment]
Logo
**Checkmarx One – Scan Summary & Details** – [3e3e580e\-4324\-4159\-8c6c\-ba689ff0ebba](https://eu.ast.checkmarx.net/projects/641c4d0f-0dae-4786-973b-ead9338157fd/scans?id=3e3e580e-4324-4159-8c6c-ba689ff0ebba&branch=ridhimamathur%2Ffix-alert-reference-9273)
### Great job! No new security vulnerabilities introduced in this pull request


---
Use @Checkmarx to interact with Checkmarx PR Assistant. 
*Examples:*
`@Checkmarx how are you able to help me?`
`@Checkmarx rescan this PR`

File: docker/scripts/scripts/httpsender/Alert_on_HTTP_Response_Code_Errors.js [hunk 1]
```diff
@@ -82,6 +82,7 @@ function responseReceived(msg, initiator, helper) {
 				"This may indicate that the application is failing to handle unexpected input correctly.\n" +
 				"Raised by the 'Alert on HTTP Response Code Error' script");
 			alert.setEvidence(code.toString())
+			alert.setReference("https://www.zaproxy.org/docs/alerts/script-http-response-code-error-" + code)
```
Comment (psiinon) [inline docker/scripts/scripts/httpsender/Alert_on_HTTP_Response_Code_Errors.js]: This is not the correct fix.
The alerts should be updated with `.setAlertRef(getId() + "-" + x);` where x is 1, 2, etc

Comment (psiinon) [reply docker/scripts/scripts/httpsender/Alert_on_HTTP_Response_Code_Errors.js]: Also add a line to https://github.com/zaproxy/zaproxy/blob/main/docker/CHANGELOG.md

Comment (ridhimamathur) [reply docker/scripts/scripts/httpsender/Alert_on_HTTP_Response_Code_Errors.js]: Thanks for the feedback. I've updated the script to use setAlertRef(pluginid + "-" + code) so each alert has a unique reference and added the changelog entry.

File: docker/scripts/scripts/httpsender/Alert_on_HTTP_Response_Code_Errors.js [hunk 2]
```diff
@@ -82,6 +82,7 @@ function responseReceived(msg, initiator, helper) {
 				"This may indicate that the application is failing to handle unexpected input correctly.\n" +
 				"Raised by the 'Alert on HTTP Response Code Error' script");
 			alert.setEvidence(code.toString())
+			alert.setAlertRef(pluginid + "-" + code)
```
Comment (psiinon) [inline docker/scripts/scripts/httpsender/Alert_on_HTTP_Response_Code_Errors.js]: The codes must start from 1 and be sequencial, so 1 and 2

File: docker/CHANGELOG.md [hunk 3]
```diff
@@ -1,6 +1,9 @@
 # Changelog
 All notable changes to the docker containers will be documented in this file.
 
+### 2026-03-09
+- Fix duplicate alert references in "Alert on HTTP Response Code Errors" script.
```
Comment (thc202) [inline docker/CHANGELOG.md]: `- Use alert references … ` also add issue to end of the entry `(Issue 9273).`

File: docker/scripts/scripts/httpsender/Alert_on_HTTP_Response_Code_Errors.js [hunk 4]
```diff
@@ -82,6 +82,12 @@ function responseReceived(msg, initiator, helper) {
 				"This may indicate that the application is failing to handle unexpected input correctly.\n" +
 				"Raised by the 'Alert on HTTP Response Code Error' script");
 			alert.setEvidence(code.toString())
+			var alertRef = 1
+			if (code >= 500)
+			{
+				alertRef = 2
```
Comment (thc202) [inline docker/scripts/scripts/httpsender/Alert_on_HTTP_Response_Code_Errors.js]: Add to the existing condition.

File: docker/scripts/scripts/httpsender/Alert_on_HTTP_Response_Code_Errors.js [hunk 5]
```diff
@@ -29,12 +29,16 @@ function responseReceived(msg, initiator, helper) {
...
+			var alertRef = 1
 			var title = "A Client Error response code was returned by the server"
+
 			if (code >= 500) {
 				// Server error
 				risk = 1	// Low
 				title = "A Server Error response code was returned by the server"
+				alertRef = 2
 			}
+
```
Comment (psiinon) [inline docker/scripts/scripts/httpsender/Alert_on_HTTP_Response_Code_Errors.js]: Please remove the blank lines you've added

File: docker/CHANGELOG.md (hunk 3 above)
Comment (thc202) [reply docker/CHANGELOG.md]: Dot after the issue.

**Comment by thc202** [comment]
Thank you!
